/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Assassin's Creed",
  "description": "Just playing around",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/img/bitbug_favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "frontmatter": {},
      "regularPath": "/blog/",
      "relativePath": "blog/README.md",
      "key": "v-407fd998",
      "path": "/blog/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/img/assassin.jpg",
        "heroText": "这一切是无法阻挡的",
        "tagline": "Jack",
        "actionText": "看一看 →",
        "actionLink": "/blog/",
        "features": [
          {
            "title": "时间",
            "details": "我曾经拥有自由，却未感受到它。"
          },
          {
            "title": "教条",
            "details": "教条本身更像是一种警告"
          },
          {
            "title": "权力",
            "details": "Free isn't given,it is taken."
          }
        ],
        "footer": "MIT Licensed | Copyright © 2021-present jack cheng"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-92d16696",
      "path": "/",
      "lastUpdated": "5/6/2021, 11:28:50 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/config.html",
      "relativePath": "config.md",
      "key": "v-220b06ee",
      "path": "/config.html",
      "lastUpdated": "5/6/2021, 11:28:50 AM"
    },
    {
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-36f68e70",
      "path": "/guide/"
    }
  ],
  "themeConfig": {
    "sidebarDepth": 4,
    "lastUpdated": "Last Updated",
    "repo": "https://github.com/chengkai2022/blog",
    "repoLabel": "我的 GitHub",
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "文章",
        "link": "/blog/"
      },
      {
        "text": "导航",
        "link": "/guide/"
      }
    ]
  }
}