/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Assassin's Creed",
  "description": "Just playing around",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/img/bitbug_favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "技术小点",
      "frontmatter": {},
      "regularPath": "/blog/",
      "relativePath": "blog/README.md",
      "key": "v-407fd998",
      "path": "/blog/",
      "lastUpdated": "5/6/2021, 4:14:39 PM"
    },
    {
      "title": "文章2",
      "frontmatter": {
        "title": "文章2"
      },
      "regularPath": "/blog/article-2.html",
      "relativePath": "blog/article-2.md",
      "key": "v-4aaae87a",
      "path": "/blog/article-2.html",
      "headers": [
        {
          "level": 2,
          "title": "Article 2",
          "slug": "article-2"
        }
      ]
    },
    {
      "title": "文章1",
      "frontmatter": {
        "title": "文章1"
      },
      "regularPath": "/blog/article-1.html",
      "relativePath": "blog/article-1.md",
      "key": "v-4617b776",
      "path": "/blog/article-1.html",
      "headers": [
        {
          "level": 2,
          "title": "Article 1",
          "slug": "article-1"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/img/assassin.jpg",
        "heroText": "这一切是无法阻挡的",
        "tagline": "Jack",
        "actionText": "看一看 →",
        "actionLink": "/blog/",
        "features": [
          {
            "title": "时间",
            "details": "我曾经拥有自由，却未感受到它。"
          },
          {
            "title": "教条",
            "details": "教条本身更像是一种警告"
          },
          {
            "title": "权力",
            "details": "Free isn't given,it is taken."
          }
        ],
        "footer": "MIT Licensed | Copyright © 2021-present jack cheng"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-92d16696",
      "path": "/",
      "lastUpdated": "5/6/2021, 4:14:39 PM"
    },
    {
      "title": "导航之路",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-36f68e70",
      "path": "/guide/",
      "lastUpdated": "5/6/2021, 4:14:39 PM"
    },
    {
      "frontmatter": {},
      "regularPath": "/config.html",
      "relativePath": "config.md",
      "key": "v-220b06ee",
      "path": "/config.html",
      "lastUpdated": "5/6/2021, 11:28:50 AM"
    }
  ],
  "themeConfig": {
    "sidebarDepth": 4,
    "lastUpdated": "Last Updated",
    "repo": "https://github.com/chengkai2022/blog",
    "repoLabel": "我的 GitHub",
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "文章",
        "link": "/blog/"
      },
      {
        "text": "导航",
        "link": "/guide/"
      }
    ],
    "sidebar": {
      "/blog/": [
        "",
        "article-1",
        "article-2"
      ],
      "/guide/": [
        ""
      ]
    },
    "smoothScroll": true
  }
}